services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Nesrine29
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: nesrine        # Different username
      MYSQL_PASSWORD: Nesrine29
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3307:3306"