version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: Nesrine29
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 